name: Deploy Helm chart to cluster
on:
  workflow_call:
    inputs:
      runs_on:
        description: "Job's runs-on parameter"
        type: string
        required: false
        default: '["self-hosted", "can-run-small-job"]'
      # Helm chart parameters
      chart_name:
        description: "Helm chart name e.g. <helm-uls-component>"
        type: string
        required: true
      chart_release:
        description: "Helm chart release name"
        type: string
        required: true
      chart_version:
        description: "Helm chart package version"
        type: string
        required: true
      namespace:
        description: "Namespace for installing helm chart"
        type: string
        required: true
      values_path:
        description: "Path to values.yaml in repo"
        required: true
        type: string
      # Image parameters (docker image)
      image_repository:
        description: "image repository"
        type: string
        required: true
      image_tag:
        description: "image tag"
        type: string
        required: true
      image_tag_path:
        description: "Image tag path into values.yaml"
        type: string
        default: "image.tag"
        required: false
      # AWS parameters
      aws_account_id:
        description: "AWS account id for ECR"
        required: true
        type: string
      aws_region:
        description: "AWS region for ECR"
        required: true
        type: string
      cluster_name:
        description: "Name of AWS EKS cluster"
        type: string
        required: true
      # BUILD and PUSH step
      build_and_push_step_env:
        description: |
          Environment variables in json string format
          # example:
          build_and_push_step_env: |
            {
              "ECR_REGISTRY": "716309063777.dkr.ecr.us-east-1.amazonaws.com",
              "ECR_REPO": "ch-file-writer",
              "IMAGE_TAG": "master-${{ github.run_number }}-${{ github.run_attempt }}"
            }
        type: string
        required: false
      build_and_push_step_run:
        description: "Step for build and push image custom for many repos"
        type: string
        required: false
        default: |
          IMAGE_FULL_NAME="${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
          PYTHON_TAG=$(grep --max-count 1 -P '^ARG PYTHON_IMAGE=python:.+$' ./Dockerfile | cut -d "=" -f 2)
          
          docker build . \
            --tag ${IMAGE_FULL_NAME} \
            --build-arg PYTHON_IMAGE=harbor.tools.improvado.io/hub-cache/library/${PYTHON_TAG}
          docker push "${IMAGE_FULL_NAME}"
          echo "::notice title=Pushed image to repo ${IMAGE_REPO}::Image that was pushed: ${IMAGE_FULL_NAME}"

concurrency:
  group: ${{ github.ref }}--deploy-via-helm
  cancel-in-progress: false

permissions:
  id-token: write
  actions: read
  checks: read
  contents: read
  pull-requests: read
  statuses: write

jobs:
  deploy:
    name: Install helm ${{ inputs.chart_release }} release
    timeout-minutes: 20
    runs-on: ${{ fromJson(inputs.runs_on) }}
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.tools.improvado.io
          username: ${{ secrets.GH_ACTIONS_HARBOR_LOGIN }}
          password: ${{ secrets.GH_ACTIONS_HARBOR_PASSWORD }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github_actions_ecr_${{ inputs.chart_name }}
          role-session-name: github_actions_ecr_${{ inputs.chart_name }}_${{ inputs.chart_release }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: "no"
      - name: Login Helm to Amazon ECR
        run: |
          aws ecr get-login-password | helm registry login \
            --username AWS \
            --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com
      - name: Login to Kubernetes cluster
        run: |
          aws eks update-kubeconfig \
            --name ${{ inputs.cluster_name }}
      - name: Install helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.9.0
      - name: Pull helm chart from ECR
        run: |
          helm pull oci://${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/{{ inputs.chart_name }} \
            --version ${{ inputs.chart_version }}
      - name: Build and push image to ECR
        env:
          ${{ fromJson( inputs.build_and_push_step_env ) }}
        run: |
          ${{ inputs.build_and_push_step_run }}
      - name: Install/upgrade helm chart to Kubernetes cluster
        run: |
          helm upgrade ${{ inputs.chart_release }} ./${{ inputs.chart_name }}-${{ inputs.chart_version }}.tgz \
            --wait \
            --install \
            -f ${GITHUB_WORKSPACE}/k8s/${{ inputs.values_path }} \
            -n ${{ inputs.namespace }} \
            --set ${{ inputs.image_tag_path }}=${{ inputs.image_tag }} \
            --timeout 15m0s \
            --debug
      - name: Add notice with release info
        run: |
          MESSAGE="
          Chart: ${{ inputs.chart }};
          Release: ${{ inputs.chart_release }};
          Version: ${{ inputs.chart_version }};
          Image Tag: ${{ inputs.image_tag }};
          "
          echo "::notice title=Installed chart::${MESSAGE//$'\n'/'%0A'}"
