name: Build and Push Helm chart
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      aws_region:
        required: true
        type: string

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ["self-hosted", "can-run-small-job"]
    timeout-minutes: 1
    outputs:
      chart_tag: ${{ steps.form_chart_tag.outputs.value }}
    steps:
      - name: Extract branch name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - name: Form Chart Tag name
        id: form_chart_tag
        run: |
          TAG=${GITHUB_REF#refs/heads/}-${{ github.run_number }}-${{ github.run_attempt }}
          if [[ ${{ github.event_name }} == "pull_request" ]] then;
            TAG=pr-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.run_attempt }}
          fi
          echo "::set-output name=value::${TAG}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github_actions_ecr_${{ inputs.project_name }}
          role-session-name: github_actions_ci_${{ inputs.project_name }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: "no"
      - name: Install helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.9.0
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ inputs.aws_region }} \ 
          | helm registry login \
            --username AWS \
            --password-stdin \
            ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com
      - name: Create and push package to ECR
        run: |
          helm package ${{ inputs.project_name }} --version ${{ steps.form_chart_tag.outputs.value }}
          helm push ${{ inputs.project_name }}-${{ steps.form_chart_tag.outputs.value }}.tgz oci://${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/
          echo "::notice title=Pushed package::${{ inputs.project_name }} that's been pushed: ${{ inputs.project_name }}-${{ steps.form_chart_tag.outputs.value }}"

